name: Release and Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version Name
        required: true


jobs:
  prodRelease:
    if: ${{ inputs.TRIGGER_EVENT == 'push' }}
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install conventional-changelog-conventionalcommits
          
      - name: Bump version, tag commit, and create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.1
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          skip-git-pull: true
          version-file: './package.json,./package-lock.json'
          config-file-path: '.github/config/config.js'

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

  preProdRelease:
    if: ${{ inputs.TRIGGER_EVENT == 'workflow_dispatch' }}
    name: Continuous Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          fetch-depth: 0
          
      - name: Check String
        run: |
          if [[ ${{ github.event.inputs.version }} != *"beta"* ]]; then
            echo "Error: The version does not contain the string beta"
            exit 1
          fi

      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          prerelease: true
